### PR TITLE
Bump angular to 4.1.1, angular/cli to 1.0.2.

### PR DESCRIPTION
**Pull request by t-p-l-k**
Updated packages to latest available versions.
Updated angular CLI config to work with new version.
Fixed karma config due to CLI update.
Fixed source files so they compile correctly.

### CODE REVIEW

**Comment by somombo** [comment]
oh thanks!

**Comment by somombo** [comment]
@t-p-l-k Thank you. 

Note that angular2-material has changed. See 
- https://material.angular.io/guide/getting-started
- https://github.com/angular/angular-cli/wiki/stories-include-angular-material

And also some of the defaults for a project created with `ng new` e.g. package.json scripts are now different

**Comment by t-p-l-k** [comment]
@somombo no problem.
Yeah, I know about the changes. I just bumped packages and fixed compiler/runtime errors which I was getting. I didn't update the project to match all present requirements.

**Comment by somombo** [comment]
LTM

**Pull request merged**
